apiVersion: apps/v1
kind: Deployment
metadata:
  name: rpg-api
  namespace: {{ .Values.namespace }}
  labels:
    app: rpg-api
  annotations:
    checkov.io/skip1: "CKV_K8S_43=Dev local Kind : image chargee via kind load docker-image, pas de digest disponible. En prod (ghcr.io) l'image est epinglee par digest et signee via Cosign."
    checkov.io/skip2: "CKV_K8S_15=IfNotPresent requis pour kind load docker-image, l'image locale n'existe dans aucun registre a pull."
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: rpg-api
  template:
    metadata:
      labels:
        app: rpg-api
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: {{ .Values.podSecurity.runAsUser }}
        runAsGroup: {{ .Values.podSecurity.runAsGroup }}
        fsGroup: {{ .Values.podSecurity.fsGroup }}
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: rpg-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          env:
            - name: API_DB_PATH
              value: {{ .Values.dbPath }}
          volumeMounts:
            - name: secrets
              mountPath: /etc/secrets
              readOnly: true
            - name: data
              mountPath: /app/data
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.containerPort }}
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.containerPort }}
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
          securityContext:
            runAsNonRoot: true
            runAsUser: {{ .Values.podSecurity.runAsUser }}
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
      volumes:
        - name: secrets
          secret:
            secretName: {{ .Values.secret.name }}
        - name: data
          persistentVolumeClaim:
            claimName: rpg-api-data
