apiVersion: apps/v1
kind: Deployment
metadata:
  name: rpg-api
  namespace: rpg-pipeline
  labels:
    app: rpg-api
  annotations:
    checkov.io/skip1: "CKV_K8S_43=Dev local Kind : image chargee via kind load docker-image, pas de digest disponible. En prod (ghcr.io) l'image est epinglee par digest et signee via Cosign."
    checkov.io/skip2: "CKV_K8S_15=IfNotPresent requis pour kind load docker-image, l'image locale n'existe dans aucun registre a pull."
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rpg-api
  template:
    metadata:
      labels:
        app: rpg-api
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "rpg-api"
        vault.hashicorp.com/secret-volume-path: "/etc/secrets"

        vault.hashicorp.com/agent-inject-secret-API_SECRET_KEY: "secret/data/rpg-api"
        vault.hashicorp.com/agent-inject-file-API_SECRET_KEY: "API_SECRET_KEY"
        vault.hashicorp.com/agent-inject-template-API_SECRET_KEY: |
          {{- with secret "secret/data/rpg-api" -}}{{ .Data.data.API_SECRET_KEY }}{{- end }}

        vault.hashicorp.com/agent-inject-secret-ADMIN_USERNAME: "secret/data/rpg-api"
        vault.hashicorp.com/agent-inject-file-ADMIN_USERNAME: "ADMIN_USERNAME"
        vault.hashicorp.com/agent-inject-template-ADMIN_USERNAME: |
          {{- with secret "secret/data/rpg-api" -}}{{ .Data.data.ADMIN_USERNAME }}{{- end }}

        vault.hashicorp.com/agent-inject-secret-ADMIN_PASSWORD: "secret/data/rpg-api"
        vault.hashicorp.com/agent-inject-file-ADMIN_PASSWORD: "ADMIN_PASSWORD"
        vault.hashicorp.com/agent-inject-template-ADMIN_PASSWORD: |
          {{- with secret "secret/data/rpg-api" -}}{{ .Data.data.ADMIN_PASSWORD }}{{- end }}
    spec:
      serviceAccountName: rpg-api
      automountServiceAccountToken: true
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: rpg-api
          image: rpg-api:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          env:
            - name: API_DB_PATH
              value: /app/data/database.db
          volumeMounts:
            - name: data
              mountPath: /app/data
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 20
          securityContext:
            runAsNonRoot: true
            runAsUser: 10001
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: rpg-api-data
