name: RPG

on:
  push:
    branches:
      - main

jobs:
  analyse:
    runs-on: ubuntu-latest
    
    steps:
      - name: Téléchargement du code source
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Installation de Cppcheck
        run: sudo apt-get install -y cppcheck

      - name: Recherche de bugs dans le code C++
        run: |
          cppcheck \
            --enable=warning,performance,portability \
            --suppress=missingIncludeSystem \
            rpg-source/

      - name: Construction de l'image Docker
        run: docker build -t rpg-alterdune .